server:
  error:
    include-stacktrace: on_param

spring:
  dataSource:
    url: jdbc:mysql://:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        #Se tivéssemos prepared statements, mostraria os parâmetros
        #type:
        #  descriptor:
        #    sql:
        #      BasicBinder: TRACE
    